<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="TypeScript\confirmarSenha.ts" />
    <Content Include="TypeScript\mapeamento.ts" />
    <Content Include="TypeScript\mesa.ts" />
    <Content Include="TypeScript\site.ts" />
    <Content Include="TypeScript\tabelaUsuario.ts" />
    <Content Include="TypeScript\usuario.ts" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\js\" />
  </ItemGroup>

</Project>
