CREATE DATABASE GASTROLINK;

USE GASTROLINK;

--Trigrama TPU
CREATE TABLE TB_TIPOS_USUARIOS(
	TPU_ID INT IDENTITY,
	TPU_TIPO VARCHAR(100) NOT NULL,
	CONSTRAINT PK_TPU PRIMARY KEY (TPU_ID)
);

INSERT INTO TB_TIPOS_USUARIOS VALUES ('ADMINISTRADOR'), ('GERENTE'), ('GARÇOM'), ('COZINHA'), ('CAIXA');

--Trigrama USU
CREATE TABLE TB_USUARIOS(
	USU_ID INT IDENTITY,
	USU_NOME VARCHAR(200) NOT NULL,
	USU_LOGIN VARCHAR(100) NOT NULL,
	USU_SENHA VARCHAR(MAX) NOT NULL,
	USU_STATUS BIT NOT NULL,
	USU_TPU_ID INT NOT NULL,
	CONSTRAINT PK_USU PRIMARY KEY (USU_ID),
	CONSTRAINT UQ_USU_LOGIN UNIQUE (USU_LOGIN),
	CONSTRAINT FK_TPU_USU FOREIGN KEY (USU_TPU_ID) REFERENCES TB_TIPOS_USUARIOS (TPU_ID)
)

INSERT INTO TB_USUARIOS(USU_NOME, USU_LOGIN, USU_SENHA, USU_STATUS, USU_TPU_ID) VALUES
('JOÃO PEDRO GEROTTO FERNANDES','joao.fernandes','123',1,1);

INSERT INTO TB_USUARIOS(USU_NOME, USU_LOGIN, USU_SENHA, USU_STATUS, USU_TPU_ID) VALUES
('GARÇOM','usuario.garcom','123',1,3);

--Trigrama FPG
CREATE TABLE TB_FORMAS_PAGAMENTO(
	FPG_ID INT IDENTITY,
	FPG_FORMA VARCHAR(100)
	CONSTRAINT PK_FPG PRIMARY KEY (FPG_ID)
);

--Trigrama CTP
CREATE TABLE TB_CATEGORIAS_PRATO(
	CTP_ID INT IDENTITY,
	CTP_CATEGORIA VARCHAR(100) NOT NULL,
	CONSTRAINT PK_CTP PRIMARY KEY (CTP_ID)
)

--Trigrama STM
CREATE TABLE TB_STATUS_MESA(
	STM_ID INT IDENTITY,
	STM_STATUS VARCHAR(100) NOT NULL,
	CONSTRAINT PK_STM PRIMARY KEY (STM_ID)
);
INSERT INTO TB_STATUS_MESA VALUES('LIVRE'),('OCUPADO'),('PEDIDO EM PREPARO'),('AGUARDANDO PAGAMENTO')

--Trigrama STP
CREATE TABLE TB_STATUS_PEDIDO(
	STP_ID INT IDENTITY,
	STP_STATUS VARCHAR(100) NOT NULL
	CONSTRAINT PK_STP PRIMARY KEY (STP_ID)
);
INSERT INTO TB_STATUS_PEDIDO VALUES
('CRIADO'),('ENVIADO PARA COZINHA'),('EM PREPARO'),('PRONTO'),('ENTREGUE'),('AGUARDANDO PAGAMENTO'),('FINALIZADO')

--Trigrama MSA
CREATE TABLE TB_MESAS(
	MSA_ID INT IDENTITY,
	MSA_NUMERO VARCHAR(10) NOT NULL,
	MSA_STM_ID INT NOT NULL,
	MSA_POSICAO_X INT,
	MSA_POSICAO_Y INT,
	CONSTRAINT PK_MSA PRIMARY KEY (MSA_ID),
	CONSTRAINT FK_MSA_STP FOREIGN KEY (MSA_STM_ID) REFERENCES TB_STATUS_MESA (STM_ID)
);

--Trigrama PRT
CREATE TABLE TB_PRATOS(
	PRT_ID INT IDENTITY,
	PRT_NOME VARCHAR(150) NOT NULL,
	PRT_DESCRICAO VARCHAR(MAX) NOT NULL,
	PRT_PRECO DECIMAL(10,2) NOT NULL,
	PRT_TEMPO_MEDIO_PREPARO INT NOT NULL,
	PRT_DISPONIBILIDADE BIT NOT NULL,
	PRT_CAT_ID INT NOT NULL,
	CONSTRAINT PK_PRT PRIMARY KEY (PRT_ID),
	CONSTRAINT FK_PRT_CAT FOREIGN KEY (PRT_CAT_ID) REFERENCES TB_PRATOS (PRT_ID)
);

--Trigrama PDD
CREATE TABLE TB_PEDIDOS(
	PDD_ID INT IDENTITY,
	PDD_TOTAL DECIMAL(10,2) NOT NULL,
	PDD_USU_ID INT NOT NULL,
	PDD_MSA_ID INT NOT NULL,
	CONSTRAINT PK_PDD PRIMARY KEY (PDD_ID),
	CONSTRAINT FK_PDD_USU FOREIGN KEY (PDD_USU_ID) REFERENCES TB_USUARIOS (USU_ID),
	CONSTRAINT FK_PDD_MSA FOREIGN KEY (PDD_MSA_ID) REFERENCES TB_MESAS (MSA_ID)
);


--Trigrama ITP
CREATE TABLE TB_ITENS_PEDIDO(
	ITP_QUANTIDADE INT NOT NULL,
	ITP_OBSERVACAO VARCHAR(MAX),
	ITP_PDD_ID INT NOT NULL,
	ITP_PRT_ID INT NOT NULL,
	CONSTRAINT PK_ITP PRIMARY KEY (ITP_PDD_ID, ITP_PRT_ID),
	CONSTRAINT FK_ITP_PDD FOREIGN KEY (ITP_PDD_ID) REFERENCES TB_PEDIDOS (PDD_ID),
	CONSTRAINT FK_ITP_PRT FOREIGN KEY (ITP_PRT_ID) REFERENCES TB_PRATOS (PRT_ID)
);

--Trigrama PAG
CREATE TABLE TB_PAGAMENTOS(
	PAG_ID INT NOT NULL,
	PAG_DESCONTO DECIMAL NOT NULL,
	PAG_VALOR_TOTAL DECIMAL NOT NULL,
	PAG_VALOR_PAGO DECIMAL NOT NULL,
	PAG_PDD_ID INT NOT NULL,
	CONSTRAINT PK_PAG PRIMARY KEY (PAG_ID),
	CONSTRAINT FK_PAG_PDD FOREIGN KEY (PAG_PDD_ID) REFERENCES TB_PEDIDOS (PDD_ID)
);