CREATE OR ALTER PROCEDURE PR_S_VALIDAR_LOGIN(
	@LOGIN VARCHAR(150)
)
AS
BEGIN

	SELECT * FROM TB_USUARIOS USU
	JOIN TB_TIPOS_USUARIOS TPU ON TPU.TPU_ID = USU.USU_TPU_ID
	WHERE USU_LOGIN = @LOGIN AND USU_STATUS = 1
END
GO

CREATE OR ALTER PROCEDURE PR_S_CONSULTAR_MESAS
AS
BEGIN
	SELECT * FROM TB_MESAS MSA
	JOIN TB_STATUS_MESA STM ON MSA.MSA_STM_ID = STM.STM_ID
END
GO

CREATE OR ALTER PROCEDURE PR_I_CADASTRAR_MESA
(
	@NUMERO_MESA VARCHAR(10)
)
AS
BEGIN
	INSERT INTO TB_MESAS (MSA_NUMERO, MSA_STM_ID) VALUES (@NUMERO_MESA,1);
END
GO

CREATE OR ALTER PROCEDURE PR_U_LAYOUT_MESA
    @Mesas MESA_POSICAO_TYPE READONLY
AS
BEGIN

    UPDATE M
    SET 
        M.MSA_POSICAO_X = T.PosX,
        M.MSA_POSICAO_Y = T.PosY
    FROM TB_MESAS M
    INNER JOIN @Mesas T ON M.MSA_ID = T.Id;

END
GO

CREATE OR ALTER PROCEDURE PR_S_CONSULTA_TIPOS_USUARIOS
AS 
BEGIN
	SELECT * FROM TB_TIPOS_USUARIOS
END
GO

CREATE OR ALTER PROCEDURE PR_I_CADASTRO_USUARIO
	@NOME AS VARCHAR(MAX),
	@LOGIN AS VARCHAR(MAX),
	@SENHA AS VARCHAR(MAX),
	@ID_TIPO_USUARIO INT
AS
BEGIN
	INSERT INTO TB_USUARIOS (USU_NOME, USU_LOGIN, USU_SENHA, USU_TPU_ID, USU_STATUS) 
	VALUES (@NOME, @LOGIN, @SENHA, @ID_TIPO_USUARIO, 1);
END
GO

CREATE OR ALTER PROCEDURE PR_S_TODOS_USUARIOS
AS
BEGIN
	SELECT * FROM TB_USUARIOS U
	JOIN TB_TIPOS_USUARIOS TPU ON U.USU_TPU_ID = TPU.TPU_ID
END
GO

CREATE OR ALTER PROCEDURE PR_S_USUARIO_POR_ID
	@ID_USUARIO INT
AS
BEGIN
	SELECT * FROM TB_USUARIOS U
	JOIN TB_TIPOS_USUARIOS TPU ON U.USU_TPU_ID = TPU.TPU_ID
	WHERE U.USU_ID = @ID_USUARIO
END
GO

CREATE OR ALTER PROCEDURE PR_U_USUARIO
	@NOME AS VARCHAR(MAX),
	@LOGIN AS VARCHAR(MAX),
	@ID_TIPO_USUARIO INT,
	@ID_USUARIO INT
AS
BEGIN
	UPDATE TB_USUARIOS SET 
		USU_NOME = @NOME,
		USU_LOGIN = @LOGIN,
		USU_TPU_ID = @ID_TIPO_USUARIO
	WHERE USU_ID = @ID_USUARIO
END
GO

CREATE OR ALTER PROCEDURE PR_U_STATUS_USUARIO
	@ID_USUARIO INT,
	@STATUS BIT
AS
BEGIN
	UPDATE TB_USUARIOS SET 
		USU_STATUS = @STATUS
	WHERE USU_ID = @ID_USUARIO
END
GO

CREATE OR ALTER PROCEDURE PR_I_CATEGORIA_PRATO
	@CATEGORIA NVARCHAR(MAX)
AS
BEGIN
	INSERT INTO TB_CATEGORIAS_PRATO (CTP_CATEGORIA) VALUES (@CATEGORIA);
END
GO