CREATE OR ALTER PROCEDURE PR_S_VALIDAR_LOGIN(
	@LOGIN VARCHAR(150),
	@SENHA VARCHAR(150)
)
AS
BEGIN

	SELECT * FROM TB_USUARIOS USU
	JOIN TB_TIPOS_USUARIOS TPU ON TPU.TPU_ID = USU.USU_TPU_ID
	WHERE USU_LOGIN = @LOGIN AND USU_SENHA = @SENHA AND USU_STATUS = 1
END

CREATE OR ALTER PROCEDURE PR_S_CONSULTAR_MESAS
AS
BEGIN
	SELECT * FROM TB_MESAS MSA
	JOIN TB_STATUS_MESA STM ON MSA.MSA_STM_ID = STM.STM_ID
END


CREATE OR ALTER PROCEDURE PR_I_CADASTRAR_MESA
(
	@NUMERO_MESA VARCHAR(10)
)
AS
BEGIN
	INSERT INTO TB_MESAS (MSA_NUMERO, MSA_STM_ID) VALUES (@NUMERO_MESA,1);
END

CREATE OR ALTER PROCEDURE PR_U_LAYOUT_MESA
    @Mesas MESA_POSICAO_TYPE READONLY
AS
BEGIN

    UPDATE M
    SET 
        M.MSA_POSICAO_X = T.PosX,
        M.MSA_POSICAO_Y = T.PosY
    FROM TB_MESAS M
    INNER JOIN @Mesas T ON M.MSA_ID = T.Id;

END