USE GASTROLINK

CREATE TYPE MESA_POSICAO_TYPE AS TABLE
(
    Id INT,
    PosX INT,
    PosY INT
);

CREATE TYPE ITENS_PEDIDOS_TYPE AS TABLE(
    ID_PRATO INT,
    OBSERVACAO VARCHAR(MAX),
    QUANTIDADE INT
)