CREATE VIEW VW_PRATOS_CARDAPIO
AS
	SELECT 
		CP.CTP_ID,
		CP.CTP_CATEGORIA AS CATEGORIA,
		P.PRT_ID,
		P.PRT_NOME AS NOME,
		P.PRT_PRECO AS PRECO,
		P.PRT_DESCRICAO AS DESCRICAO,
		P.PRT_TEMPO_MEDIO_PREPARO AS TEMPO_MEDIO,
		P.PRT_URL_IMAGEM AS URL_IMAGEM
	FROM TB_CATEGORIAS_PRATO CP
	JOIN TB_PRATOS P ON CP.CTP_ID = P.PRT_CAT_ID
	WHERE P.PRT_DISPONIBILIDADE = 1
GO