CREATE VIEW VW_PRATOS_CARDAPIO
AS
	SELECT 
		CP.CTP_ID,
		CP.CTP_CATEGORIA AS CATEGORIA,
		P.PRT_ID,
		P.PRT_NOME AS NOME,
		P.PRT_PRECO AS PRECO,
		P.PRT_DESCRICAO AS DESCRICAO,
		P.PRT_TEMPO_MEDIO_PREPARO AS TEMPO_MEDIO,
		P.PRT_URL_IMAGEM AS URL_IMAGEM
	FROM TB_CATEGORIAS_PRATO CP
	JOIN TB_PRATOS P ON CP.CTP_ID = P.PRT_CAT_ID
	WHERE P.PRT_DISPONIBILIDADE = 1
GO

CREATE VIEW VW_PEDIDOS
AS
	SELECT 
		P.PDD_ID AS NUMERO_PEDIDO,
		P.PDD_TOTAL AS TOTAL,
		P.PDD_DATA AS DATA,
		M.MSA_ID AS ID_MESA,
		M.MSA_NUMERO AS NUMERO_MESA,
		PRT.PRT_ID AS ID_PRATO,
		PRT.PRT_NOME AS NOME_PRATO,
		PRT.PRT_PRECO AS PRECO,
		PRT.PRT_URL_IMAGEM AS IMAGEM,
		PRT.PRT_DESCRICAO AS DESCRICAO,
		PRT.PRT_TEMPO_MEDIO_PREPARO AS TEMPO_MEDIO,
		ITP.ITP_OBSERVACAO AS OBSERVACAO,
		ITP_QUANTIDADE AS QUANTIDADE,
		U.USU_ID AS ID_USUARIO,
		U.USU_NOME AS NOME_USUARIO,
		SP.STP_ID AS ID_STATUS,
		SP.STP_STATUS AS STATUS
	FROM TB_PEDIDOS P
	JOIN TB_ITENS_PEDIDO ITP ON P.PDD_ID = ITP.ITP_PDD_ID
	JOIN TB_PRATOS PRT ON PRT.PRT_ID = ITP.ITP_PRT_ID
	JOIN TB_USUARIOS U ON U.USU_ID = P.PDD_USU_ID 
	JOIN TB_MESAS M ON M.MSA_ID = P.PDD_MSA_ID
	JOIN TB_STATUS_PEDIDO SP ON SP.STP_ID = P.PDD_STP_ID
GO